env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Set mod key
$mod = ALT

# Terminal
bind = $mod, Return, exec, kitty

# Wofi
bind = $mod, SPACE, exec, wofi --show drun

# Close window
bind = $mod SHIFT, Q, killactive

# Reload config
bind = $mod SHIFT, C, exec, hyprctl reload

# Workspaces
bind = $mod, Y, workspace, 1
bind = $mod, O, workspace, 2
bind = $mod, U, workspace, 3
bind = $mod, I, workspace, 4
bind = $mod, A, workspace, 5
bind = $mod, E, workspace, 6

bind = $mod SHIFT, Y, movetoworkspace, 1
bind = $mod SHIFT, O, movetoworkspace, 2
bind = $mod SHIFT, U, movetoworkspace, 3
bind = $mod SHIFT, I, movetoworkspace, 4
bind = $mod SHIFT, A, movetoworkspace, 5
bind = $mod SHIFT, E, movetoworkspace, 6

# Tmux pane navigation
bind = $mod CTRL, L, exec, ~/.config/hypr/focus-tmux-pane.sh 1 1
bind = $mod CTRL, D, exec, ~/.config/hypr/focus-tmux-pane.sh 1 2
bind = $mod CTRL, H, exec, ~/.config/hypr/focus-tmux-pane.sh 2 1
bind = $mod CTRL, T, exec, ~/.config/hypr/focus-tmux-pane.sh 2 2
bind = $mod CTRL, P, exec, ~/.config/hypr/focus-tmux-pane.sh 3 1
bind = $mod CTRL, N, exec, ~/.config/hypr/focus-tmux-pane.sh 3 2

# Windows
bind = $mod SHIFT, N, fullscreen

bind = $mod SHIFT CTRL, H, movewindow, l
bind = $mod SHIFT CTRL, L, movewindow, r
bind = $mod SHIFT CTRL, K, movewindow, u
bind = $mod SHIFT CTRL, J, movewindow, d

bind = $mod SHIFT, space, togglefloating

monitor=DP-2,3840x2160@240,0x0,1.25

# Waybar
exec-once = /usr/bin/waybar

# Animations
animations {
  enabled = no
}


# Screenshot area and copy to clipboard
bind = $mod, S, exec, grim -g "$(slurp)" - | wl-copy

# Screenshot area and save to dir
bind = $mod SHIFT, S, exec, grim -g "$(slurp)" ~/Pictures/screenshot_$(date +%s).png


# Media Keybinds
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPlay, exec, playerctl play-pause

# Dont show gaps when only 1 window is on screen
workspace = w[t1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

# Hydrate workspaces on startup
exec-once = zen-browser
exec-once = kitty
exec-once = gtk-launch spotify
exec-once = gtk-launch discord

windowrule {
  name = windowrule-1
  workspace = 1
  match:class = ^(zen|Zen)$
}

windowrule {
  name = windowrule-2
  workspace = 2
  match:class = ^(kitty)$
}

windowrule {
  name = windowrule-3
  workspace = 3
  match:class = ^(spotify|Spotify)$
}

windowrule {
  name = windowrule-4
  workspace = 4
  match:class = ^(discord)$
}


# Wallpaper manager
exec-once = hyprpaper

# Monitor Idle manager
#exec-once = hypridle


